feat: see through Lens
lensterxyz/lenster pull request #1208
Opened 2022-11-15 15:38 UTC by sasicodes

## What does this PR do?

Fixes #1053 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/lensterxyz/lenster/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2022-11-16 16:00 UTC, sasicodes commented
@bigint doi

review this on side.

2022-11-17 09:22 UTC, bigint commented
@sasicodes is it ready for review?

2022-11-17 16:38 UTC, bigint requested changes

2022-11-17 16:54 UTC, sasicodes commented on src/components/Home/SeeThroughLens.tsx
> +const SeeThroughLens = () => {
any specific reason adding it?

2022-11-19 08:08 UTC, harish-sethuraman commented on src/components/Home/Highlights.tsx
> +  const profileId = seeThroughProfile?.id ?? currentProfile?.id ?? null;
```suggestion
  const profileId = seeThroughProfile?.id ?? currentProfile?.id;
```

ser? but null coersion is for adding fallback to null values?

2022-11-19 08:10 UTC, harish-sethuraman commented on src/components/Home/SeeThroughLens.tsx
> +          <img
Should we consider using next/image here? as height and width is predefined?

2022-11-19 08:11 UTC, harish-sethuraman commented on src/components/Home/SeeThroughLens.tsx
> +          <span>{seeThroughProfile ? `@${profile?.handle}` : 'My Feed'}</span>
@bigint should we consider having a component instead of always prefixing it with `@`?  WDYT

2022-11-20 13:30 UTC, bigint commented
We have migrated to monorepo, can you please sync with `main` branch 🙏🏼

2022-11-21 12:17 UTC, closed without merging