feat: show OG post of comment in detail page
lensterxyz/lenster pull request #1468
Opened 2022-12-26 10:34 UTC by sasicodes

## What does this PR do?

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/lensterxyz/lenster/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2023-01-13 05:51 UTC, sasicodes commented
Blocked by CLS in embeds and images.

2023-01-19 05:10 UTC, bigint commented
@sasicodes bls fix conflicts 🙇🏼

2023-01-19 05:11 UTC, bigint commented
This is getting cutoff

<img width="564" alt="image" src="https://user-images.githubusercontent.com/69431456/213360584-5261c52e-ee76-4a2a-9d05-8d93eabf38f3.png">

2023-01-19 05:15 UTC, bigint commented
Link T-4008

2023-01-19 06:16 UTC, sasicodes commented
> This is getting cutoff
> 
> <img alt="image" width="564" src="https://user-images.githubusercontent.com/69431456/213360584-5261c52e-ee76-4a2a-9d05-8d93eabf38f3.png">

We have set the sidebar already 👍🏻 

Two option:
- It requires scroll area so that it will not hide.
- If we reduce the extra scroll, the sidebar bit hidden

2023-01-19 07:53 UTC, bigint commented
@sasicodes It's ok to have scroll, one last thing can we handle for staff mode as well? using `useStaffMode` hook 🙇🏼 

<img width="477" alt="image" src="https://user-images.githubusercontent.com/69431456/213385232-a0b6a403-d02c-49bd-9b08-c0da556d930e.png">

2023-01-19 07:57 UTC, bigint requested changes

2023-01-19 07:57 UTC, bigint commented on apps/web/src/components/Publication/FullPublication.tsx
> +  // 0;
We can remove this comment 🗑️

2023-01-19 07:57 UTC, bigint commented on apps/web/src/components/Publication/FullPublication.tsx
> +  const mainPost = commentOn && commentOn?.__typename !== 'Mirror' ? commentOn?.mainPost : null;
Do we need `commentOn &&` condition? cuz the second one has optional chaining in it

2023-01-19 07:57 UTC, bigint commented on apps/web/src/components/Publication/FullPublication.tsx
> +    if (isGatedThread) {
```suggestion
    }

    if (isGatedThread) {
```

added space between two statements 🙇🏼

2023-01-19 07:57 UTC, bigint commented on apps/web/src/components/Publication/FullPublication.tsx
> +  // }, [threadRef, showOriginalThread]);
can remove this

2023-01-19 07:57 UTC, bigint commented on apps/web/src/components/Publication/index.tsx
> +    // const availableLinks = getURLs(data?.publication?.metadata.content);
can remove this

2023-01-19 07:59 UTC, sasicodes commented
Cleaned up 👍🏻

2023-01-19 08:24 UTC, bigint commented on apps/web/src/components/UI/GridLayout.tsx
> +  style?: React.CSSProperties;
Just import `CSSProperties` from react 🙇🏼

2023-01-19 08:24 UTC, bigint approved these changes

2023-01-19 08:24 UTC, bigint commented on apps/web/src/components/UI/GridLayout.tsx
> +  style?: React.CSSProperties;
@sasicodes one last change

2023-01-19 08:27 UTC, bigint commented
**LGTM** :shipit: 

![Rad LGTM](https://data.whicdn.com/images/28972800/original.gif)

2023-01-24 13:36 UTC, harish-sethuraman commented on apps/web/src/components/Publication/ThreadBody.tsx
> +  intersectionRef?: any;
Nice `any`

2023-01-24 13:37 UTC, harish-sethuraman commented on apps/web/src/components/UI/GridLayout.tsx
> +    <div className={`lg:col-span-8 md:col-span-12 col-span-12 mb-5 ${className}`} style={style}>
```suggestion
    <div className={clsx('lg:col-span-8 md:col-span-12 col-span-12 mb-5', className)} style={style}>
```

2023-03-14 04:47 UTC, bigint commented
@sasicodes is it good to go?

2023-03-14 04:50 UTC, sasicodes commented
> @sasicodes is it good to go?

resolved conflicts

2023-04-08 14:47 UTC, bigint commented
Closing this we will do this during redesign 🙇🏼

2023-04-08 14:47 UTC, closed without merging