chore: auto-closed status setting modal
lensterxyz/lenster pull request #1870
Opened 2023-02-27 15:52 UTC by jhd2best

## What does this PR do?
as https://github.com/lensterxyz/lenster/issues/1844 request. we add auto-closed status setting bar feature in this PR

![image](https://user-images.githubusercontent.com/8352895/221611713-928a91ba-b5d0-4ebb-a853-f07d5978fcf8.png)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?
- [ ] Login to Lenster
- [ ] Navigate to the top right corner, click on the display picture
- [ ] Select the option "Set status" from the drop down (will open a dialog box)
- [ ] Update the required status in the box and click on "Save"
- [ ] Check whether status setting modal auto-closed

## Checklist
- I have read the [contributing guide](https://github.com/lensterxyz/lenster/blob/main/CONTRIBUTING.md)
- My code follow the style guidelines of this project
- I have performed a self-review of my own code and corrected any misspellings
- I have commented my code, particularly in hard-to-understand areas
- I have checked if my PR needs changes to the documentation
- I have checked if my changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- I have checked if new and existing unit tests pass locally with my changes

2023-02-27 17:24 UTC, bigint requested changes

2023-02-27 17:24 UTC, bigint commented on apps/web/src/components/Shared/Status.tsx
> +import { useGlobalModalStateStore } from '../../store/modals';
better use `import { useGlobalModalStateStore } from 'src/store/modals';`

2023-02-27 17:24 UTC, bigint commented on .gitignore
> +# jetbrains IDE
```suggestion
# JetBrains IDE
```

2023-02-27 17:27 UTC, bigint commented
Closes T-6926

2023-02-28 00:31 UTC, jhd2best commented on apps/web/src/components/Shared/Status.tsx
> +import { useGlobalModalStateStore } from '../../store/modals';
sure. updated

2023-02-28 06:14 UTC, bigint approved these changes
**LGTM** :shipit: 

![Rad LGTM](https://data.whicdn.com/images/28972800/original.gif)

2023-02-28 06:14 UTC, merged