fixes and testing
lensterxyz/lenster pull request #2884
Opened 2023-05-18 13:39 UTC by Seroxdesign

## What does this PR do?

Integrate Synpress with Playwright for e2e web3 testing

## Related issues

Fixes #2170

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Explanation of the changes

Added synpress to testing folders, added tags to buttons so that we can identify and click them in tests

## Emoji

(💯

2023-06-01 05:16 UTC, bigint requested changes

2023-06-01 05:16 UTC, bigint commented on apps/web/src/components/Shared/Login/WalletSelector.tsx
> +            id="lenster-login"
we always use `data-testid`

2023-06-01 05:16 UTC, bigint commented on tests/playwright.config.ts
Lot of things changed in this file, it will break ci 😕

2023-06-01 08:30 UTC, Seroxdesign commented
On it

2023-06-13 03:36 UTC, bigint commented
Closing this of being PR got stale for 2 weeks 🙇🏼 😕

2023-06-13 03:36 UTC, closed without merging