Rainbow Wallet Migration
lensterxyz/lenster pull request #3418
Opened 2023-08-02 14:52 UTC by spantheslayer

## What does this PR do?
Implements #3398 

## Related issues
PR is in WIP

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-08-02 15:12 UTC, bigint requested changes

2023-08-02 15:13 UTC, bigint commented on apps/web/next.config.js
> +  },
Is this a requirement from rainbow kit?

2023-08-02 15:27 UTC, spantheslayer commented on apps/web/next.config.js
> +  },
yes, otherwise, rainbowconnector breaks

2023-08-03 06:22 UTC, bigint commented
We don't want now 🙇🏼

2023-08-03 06:22 UTC, closed without merging