draft: unkownmodules support
lensterxyz/lenster pull request #786
Opened 2022-10-11 12:37 UTC by arttu0

## What does this PR do?

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/lensterxyz/lenster/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

2022-10-14 11:48 UTC, bigint requested changes

2022-10-14 11:48 UTC, bigint commented on data/contracts.ts
> +export const MAINNET_NETUPDATEOWNABLEFEECOLLECTMODULEADDRESS = '0x432960b3209686Cc69e2EEC1dBBaB52A1c0Bf938';
**suggestion:** Better to use `_` as separator

2022-10-14 12:05 UTC, bigint commented on src/lib/getModule.ts
> +        helper: ''
We need to add some helper here 🙇🏼

2022-10-19 05:13 UTC, bigint commented
@arttu0 any updates on comments?

2022-10-19 14:30 UTC, bigint requested changes

2022-10-19 14:30 UTC, bigint commented on src/components/Publication/Actions/Collect/index.tsx
> +            ? 'Unknown Collect'
**suggestion:** I think we don't need this condition, it will bet automatically populated from `getModule` 🤔

2022-10-28 09:19 UTC, bigint commented
Can you resolve conflicts 🙏🏼

2022-11-01 16:18 UTC, bigint requested changes

2022-11-01 16:20 UTC, arttu0 commented on src/components/Publication/Actions/Collect/CollectModule.tsx
> +  const { data: moduleData, refetch } = useContractRead({
it has parameter enabled: false, so it shouldn't

2022-11-02 09:40 UTC, bigint commented on src/components/Publication/Actions/Collect/CollectModule.tsx
> +      refetch();
is this awaited? or do we need to do it?

2022-11-03 17:41 UTC, merged