Feat/new conversation
lensterxyz/lenster pull request #859
Opened 2022-10-18 11:06 UTC by bhavya2611

## What does this PR do?

Adds flow for a new conversation

Fixes # (issue)

Resetting message store and XMTP client on Account Change

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## How should this be tested?

- [ ] Try to start a new conversation
- [ ] Change Accounts and see if the message state is refreshed

Default State
![image](https://user-images.githubusercontent.com/28332178/196404975-e86a3ef6-00f0-4359-9210-81edb23607ec.png)

Search State
![image](https://user-images.githubusercontent.com/28332178/196405032-842474fc-d77d-41bb-85a4-e5045ce8624e.png)

Profile not on XMTP
![image](https://user-images.githubusercontent.com/28332178/196405083-71ae4525-46d7-4968-9b76-3aca78c4fd1c.png)

Profile on XMTP 
![image](https://user-images.githubusercontent.com/28332178/196413195-83b8084f-61e8-4a9e-ad47-44fe797bc9fd.png)

2022-10-18 14:33 UTC, bigint requested changes
@bhavya2611 left some comments

2022-10-18 14:33 UTC, bigint commented on src/components/Messages/PreviewList.tsx
> +            <PlusCircleIcon onClick={newMessageClick} className="h-6 w-6" />
**nitpick:** add onClick to button above

2022-10-18 14:33 UTC, bigint commented on src/components/Messages/PreviewList.tsx
> +    router.push('/messages/');
```suggestion
    router.push('/messages');
```

2022-10-18 14:33 UTC, bigint commented on src/components/Messages/index.tsx
> +    }
**suggestion:** we can avoid else by handling not condition first and return with setError

2022-10-18 14:37 UTC, bigint commented
Better we can use a modal when a new message button is clicked like Twitter does it

<img width="986" alt="Screenshot 2022-10-18 at 8 05 50 PM" src="https://user-images.githubusercontent.com/69431456/196460954-d74a7c8e-cef0-4caa-94f1-30aa384b57bc.png">

If nothing is selected we can show a state like this

<img width="977" alt="Screenshot 2022-10-18 at 8 06 30 PM" src="https://user-images.githubusercontent.com/69431456/196461161-a7f1d97e-c105-4fe7-9d14-df07ce712a56.png">

2022-10-18 20:47 UTC, elisealix22 reviewed
Great catch on resetting when the profile changes! Two things on my end:
1. I think we can likely clean up the `Link` vs `onClick` to use a single `onProfileSelected()` callback that defaults to opening a profile if one isn't set.
2. I too was able to duplicate a convo so we'll prob want to protect from that.

After seeing @bigint 's suggestion and chatting with @darickdang, I'm cool with using a modal for searching for new profiles if you are @bhavya2611 ! I think we'd just want to always open the convo after one is selected and eventually (follow-up PR likely) show a warning in that view if they aren't yet on the network:

<img width="925" alt="Screen Shot 2022-10-18 at 4 43 43 PM" src="https://user-images.githubusercontent.com/556051/196541066-388d4eeb-bc7c-453c-9f91-922d0ef3763d.png">

2022-10-18 20:47 UTC, elisealix22 commented on data/feature-flags.ts
> +      '0x4cc3' // iambhavya2.lens
Is this for testnet? If so, everyone should be enabled by default in testnet. Only mainnet profiles need to be allowlisted here:

https://github.com/lensterxyz/lenster/blob/bf58e32fb178d8e6be3d6035e804fbb77d1c001f/src/lib/isFeatureEnabled.ts#L7

2022-10-18 20:47 UTC, elisealix22 commented on src/components/Shared/Navbar/Search.tsx
> +                        onProfileSelected && onProfileSelected(profile);
Would it be possible to move the previous profile link to an onProfileSelected callback so we don't have competing `href` and `onClick`s and they can both use `onClick()`?

2022-10-19 06:10 UTC, bhavya2611 commented on src/components/Shared/UserProfile.tsx
> +      <Link href={linkToProfile ? `/u/${profile?.handle}` : ''}>
I think the cursor should still be pointer, as it is clickable, just it will perform different routing and not the one to profile.

2022-10-19 06:32 UTC, bhavya2611 commented
@bigint @elisealix22 with the time crunch we have do you think UX changes can be taken as enhancement and we for now keep the current flow and keep going? 

The current flow was made as per the designs we had, not that we should not change, but it might be nice to first get all stuff done have a version out and then come back to this. 

Feel free to let me know if you guys feel otherwise :D

2022-10-19 06:33 UTC, bhavya2611 commented
Also FYI - Apart from the UX change, everything else on this PR is resolved and the PR is good to merge

2022-10-19 09:24 UTC, bigint commented
Cool sure thing @bhavya2611 I added to the findings list here https://github.com/lensterxyz/lenster/issues/829

we can check this back later 🙇🏼

2022-10-19 09:25 UTC, merged